### ISSUE TITLE
where can I find 'vl_contrib' function???

### ISSUE THREAD

**Issue by fidodido2503** [albanie/mcnSSD#1]

**Comment by albanie** [comment]
Hi @fidodido2503, sorry for the slow response.  The function can be found on the `contrib` branch on the main repo [here](https://github.com/vlfeat/matconvnet/tree/contrib).

**Comment by sqyangg** [comment]
Hi, thank you for providing this code.
But when I run vl_contrib('compile', 'mcnSSD', 'contribUrl', 'github.com/albanie/matconvnet-contrib-test/') ; there is a error.
Index exceeds matrix dimensions.

Error in compile_mcnSSD>selectCompileOpts (line 24)
s = opts{1} ;

I run in step, and find opts is empty. Plz help me.
Thank you

**Comment by albanie** [comment]
Hi @sqyangg - apologies for this. I have updated the install instructions to try to make things clearer.  After switching to the `contrib` branch, you will need to recompile MatConvNet.
