### ISSUE TITLE
error in ssd_demo?

### ISSUE THREAD

**Issue by maxiaoyuelun** [albanie/mcnSSD#11]
when I run the ssd_demo.m, an error occurred in vl_nnflatten.m, the dzdy has an empty matrix, and so the error in Line 31 of vl_nnflatten.m comes.
below is the error image:

error: vl_nnflatten (line 31)
    y = reshape(dzdy{1}, sz) ;

error: dagnn.Flatten/forward (line 13)
      outputs{1} = vl_nnflatten(inputs{1}, obj.axis, []) ;

error: dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

error: dagnn.DagNN/eval (line 91)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

error ssd_demo (line 66)
  net.eval({'data', im}) 

thank you for your attention!!!

**Comment by albanie** [comment]
Good spot, thank you for reporting it!
