### ISSUE TITLE
Input #2 expected to be a cell array in "vl_nnmatchpriors"

### ISSUE THREAD

**Issue by Arminkhodaei** [albanie/mcnSSD#15]
Thank you so much @albanie. The previous problems (#14) have solved.
But I think there is something else that is going wrong in `vl_nnmatchpriors`.
When I want to use the output generated by training procedure (for example `net-epoch-50.mat`) in test mode, I face an error at the following assertion:
```
  cellfun(@(x) assert(all(all(x(:,3:4) - x(:,1:2) > 0)), ...
          'MULTIBOXCODER:invalidGroundTruthBoxes', ...
          'ground truth boxes must be in the (xmin, ymin, xmax, ymax) format'), ...
          gt) ;
```
This is the exact error message:
> Input #2 expected to be a cell array, was double instead.

I think since in this case, the `gt` argument is an empty 0x0 double array, there should be some problems.

**Comment by Arminkhodaei** [comment]
Sorry. The problem solved!
That was my own fault by making some changes in `deploy` and `evaluation` functions.

**Comment by albanie** [comment]
Ah, awesome!  :)
