### ISSUE TITLE
getCombinedPascalImdb Not exist!

### ISSUE THREAD

**Issue by Mirsadeghi** [albanie/mcnSSD#16]
Hi
I try to test training sample of SSD code on the pascal voc dataset, but got this error 
"Undefined function or variable getCombinedPascalImdb".
i look for this function but i cannot find it on the project repository! 
Also, i search this function in the google, but nothing found!

**Comment by albanie** [comment]
Hi @karajrobo, the function is defined here: https://github.com/albanie/mcnDatasets/tree/master/pascal, as part of the `mcnDatasets` module.  This should be loaded as a dependency for `mcnSSD` by the code here: https://github.com/albanie/mcnSSD/blob/master/setup_mcnSSD.m#L7, but it appears not have run in your case - apologies.

**Comment by Mirsadeghi** [comment]
Hi @albanie, Thank you for fast response.
I found the function!

**Comment by albanie** [comment]
Great!
