### ISSUE TITLE
Where is multiscale training code?

### ISSUE THREAD

**Issue by xychen9459** [albanie/mcnSSD#17]
In `ssd_pascal_evaluation.m`, I find multiscale test options:
```
% configure multiscale options
opts.msOpts.use = false ;
opts.msOpts.scales = [1 1.4] ;
```
and in `ssd_evaluation.m`, the following codes implies that two different nets are used for multiscale evaluation,
```
% select net - original SSD is stored first, otherwise use modified net
if scale == 1, net_ = net{1} ; else, net_ = net{2} ; end
```
but in training code `ssd_pascal_train.m`, there is nothing about using multiscale training to generate different networks for specified input scales. Now I am trying to add multiscale training to SSD. Could you tell me implemetation details about your multiscale training experiment or give me some referenece codes? 

Thanks.

**Comment by albanie** [comment]
Hi @xychen9459, the network is trained at a single scale, and tested at multiple scales.  This is largely for efficiency reasons  - there may be a benefit to training at multiple scales but I have not explored that option myself.

**Comment by xychen9459** [comment]
@albanie, thanks for your response. I will try some different multiscale training and testing options.
