### ISSUE TITLE
SSD not generate any prediction!

### ISSUE THREAD

**Issue by Mirsadeghi** [albanie/mcnSSD#31]
Hi @albanie 
I have trained mcnSSD on my on dataset.
everything looks good (below figure), but after training, when i test it on the validation/train set it not generate any boxes in the output.
![train_process](https://user-images.githubusercontent.com/30624737/51166658-83c12380-18b9-11e9-81e4-67de4494c152.jpg)
I carefully maintain pre-processing step in the test phase to be equal with training phase.
Note: I look at conf-loss layer during training, I observe that probability of first class (Background) higher than second class (in 2 class ssd). Do you have an recommendation to solve this problem?

**Comment by albanie** [comment]
Hi @karajrobo, apologies for the slow response.  I'm sorry to say that I can no longer provide support for this codebase - I should have added a deprecation notice sooner, so I apologise for the time you have spent facing bugs.

**Comment by Mirsadeghi** [comment]
Hi @albanie . Thank you for response. If you don't have time, i can provide support for this codebase.
if you are interested in my collaboration, feel free to contact me.
