### ISSUE TITLE
'or' in the line 178 of vl_nnmultiboxdetector.cu

### ISSUE THREAD

**Issue by wuyi1983** [albanie/mcnSSD#6]
if ((numPriors != (confPreds.getDepth() / numClasses)) or (numPriors != (locPreds.getDepth() / 4))) {
    vlmxError(VLMXE_IllegalArgument, "LOCPREDS and CONFPREDS do not match the given set of priors.") ;
  }

'or' should be replaced by '|'.

**Comment by albanie** [comment]
Good spot!
