### ISSUE TITLE
where is 'last_compile_opts.mat?

### ISSUE THREAD

**Issue by 89douner** [albanie/mcnSSD#8]
When I run compile_mcnSSD.m, matlab program throw an below error  
index exceeds matrix dimensions
error: compile_mcnSSD>selectCompileOpts (line 24)
s = opts{1} ;

error: compile_mcnSSD (line 13)
opts = selectCompileOpts(opts) ;

I guess.. that the reason for the error is that the file in this folder (vl_roontnn/matlab/mex/.build, last_compile_opts.mat) does not exist. Also, there is no folder (vl_roontnn/matlab/mex/.build).

<some parts of compile_mcnSSD.m code>
function compile_mcnSSD(varargin)
% compile the C++/CUDA components of the SSD Detector 

last_args_path = fullfile(vl_rootnn, 'matlab/mex/.build', ...
  'last_compile_opts.mat') ;
opts = {} ;

if exist(last_args_path, 'file')
  opts = {load(last_args_path)} ;
end

could you let me know some solves about this error?
Thanks..

**Comment by albanie** [comment]
Are you using a recent version of MatConvNet?  This feature was added fairly recently to make it easier to compile modules.

**Comment by albanie** [comment]
I've modified the compile script, hopefully if you update your copy and try again it might work :)

**Comment by 89douner** [comment]
your answer is right. MY version was 1.0-beta24. After changed to 1.0-beta25, mcnSSD was easily installed, compiled, setup and test. Thanks your answer!

**Comment by albanie** [comment]
Great :)
