### ISSUE TITLE
vl_argparsepos is undefined function or variable.

### ISSUE THREAD

**Issue by 89douner** [albanie/mcnSSD#9]
when I tried to run ssd_demo.m, matlab throws this error "vl_argparsepos'  Undefined function or variable. 

So, I added vl_argparsepos.m 
(from https://github.com/vlfeat/autonn/blob/master/matlab/vl_argparsepos.m) to matlab in matconvnet_root directory. And then, ssd_demo.m is successfully done.

 is this right way?

**Comment by albanie** [comment]
Yes, thanks!  After some changes to the code, I need to add autonn as a dependency.
